-- ==========================================
-- 01_schema.sql
-- Docházkový systém - instalační schema
-- ==========================================

-- Obsah:
-- - tabulky
-- - constraints
-- - indexy
-- - views
-- - triggery na updated_at


-- ==========================================
-- TABULKA: app_settings
-- ==========================================

create table if not exists public.app_settings (
  id integer primary key default 1,
  app_name text not null default 'Docházkový systém',
  company_name text not null default 'Moje firma',
  logo_url text,
  primary_color text default '#2563eb',
  support_email text,
  timezone text not null default 'Europe/Prague',
  currency text not null default 'CZK',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint app_settings_single_row check (id = 1)
);


-- ==========================================
-- TABULKA: offices
-- ==========================================

create table if not exists public.offices (
  id bigint generated by default as identity primary key,
  name text not null,
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create unique index if not exists offices_name_key
  on public.offices (name);


-- ==========================================
-- TABULKA: employees
-- ==========================================

create table if not exists public.employees (
  id bigint generated by default as identity primary key,
  name text not null,
  weekly text,
  leave_days integer not null default 20,
  leave_hours integer not null default 160,
  offices text,
  email text not null,
  auth_user_id uuid,
  is_admin boolean not null default false,
  active boolean not null default true,
  role text not null default 'employee',
  created_at timestamptz not null default now()
);

create unique index if not exists employees_email_key
  on public.employees (email);

create unique index if not exists employees_auth_user_id_key
  on public.employees (auth_user_id);
