-- ==========================================
-- 01_schema.sql
-- Docházkový systém - instalační schema
-- ==========================================

create extension if not exists pgcrypto;

-- ==========================================
-- TABULKA: app_settings
-- ==========================================

create table if not exists public.app_settings (
  id integer primary key default 1,
  app_name text not null default 'Docházkový systém',
  company_name text not null default 'Moje firma',
  logo_url text,
  primary_color text default '#2563eb',
  support_email text,
  timezone text not null default 'Europe/Prague',
  currency text not null default 'CZK',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint app_settings_single_row check (id = 1)
);

-- ==========================================
-- TABULKA: offices
-- ==========================================

create table if not exists public.offices (
  id bigint generated by default as identity primary key,
  name text not null,
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists offices_name_key
  on public.offices (name);

-- ==========================================
-- TABULKA: employees
-- ==========================================

create table if not exists public.employees (
  id bigint generated by default as identity primary key,
  name text not null,
  weekly text,
  leave_days integer not null default 20,
  leave_hours integer not null default 160,
  offices text,
  email text not null,
  auth_user_id uuid,
  is_admin boolean not null default false,
  active boolean not null default true,
  role text not null default 'employee',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint employees_role_check check (role in ('employee', 'admin'))
);

create unique index if not exists employees_email_key
  on public.employees (lower(email));

create unique index if not exists employees_auth_user_id_key
  on public.employees (auth_user_id)
  where auth_user_id is not null;

-- ==========================================
-- TABULKA: attendance
-- ==========================================

create table if not exists public.attendance (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references public.employees(id) on delete cascade,
  date date not null,
  time_from time without time zone,
  time_to time without time zone,
  office text,
  type text,
  break_minutes integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint attendance_break_minutes_check check (break_minutes >= 0),
  constraint attendance_time_order_check check (
    time_from is null
    or time_to is null
    or time_to > time_from
  ),
  constraint attendance_type_check check (
    type is null
    or type in (
      'práce',
      'home office',
      'služební cesta',
      'k lékaři',
      'dovolená',
      'work',
      'business trip',
      'doctor',
      'vacation'
    )
  )
);

create index if not exists attendance_employee_id_idx
  on public.attendance (employee_id);

create index if not exists attendance_date_idx
  on public.attendance (date);

create index if not exists attendance_employee_date_idx
  on public.attendance (employee_id, date);

-- ==========================================
-- TABULKA: attendance_audit
-- ==========================================

create table if not exists public.attendance_audit (
  id bigint generated by default as identity primary key,
  changed_at timestamptz not null default now(),
  employee_name text,
  action text,
  old_data jsonb,
  new_data jsonb
);

create index if not exists attendance_audit_changed_at_idx
  on public.attendance_audit (changed_at desc);

-- ==========================================
-- TABULKA: attendance_month_locks
-- ==========================================

create table if not exists public.attendance_month_locks (
  id bigint generated by default as identity primary key,
  month text not null,
  locked boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint attendance_month_locks_month_check check (month ~ '^\d{4}-\d{2}$')
);

create unique index if not exists attendance_month_locks_month_key
  on public.attendance_month_locks (month);

-- ==========================================
-- TABULKA: leaves
-- ==========================================

create table if not exists public.leaves (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references public.employees(id) on delete cascade,
  date_from date not null,
  date_to date not null,
  days integer not null default 1,
  hours integer not null default 8,
  type text not null default 'vacation',
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint leaves_days_check check (days >= 1),
  constraint leaves_hours_check check (hours >= 0),
  constraint leaves_date_check check (date_to >= date_from),
  constraint leaves_type_check check (type in ('vacation', 'sick', 'other'))
);

create index if not exists leaves_employee_id_idx
  on public.leaves (employee_id);

create index if not exists leaves_date_range_idx
  on public.leaves (date_from, date_to);

-- ==========================================
-- TABULKA: leave_requests
-- ==========================================

create table if not exists public.leave_requests (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references public.employees(id) on delete cascade,
  date_from date not null,
  date_to date not null,
  hours integer not null default 8,
  note text,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint leave_requests_hours_check check (hours >= 0),
  constraint leave_requests_date_check check (date_to >= date_from),
  constraint leave_requests_status_check check (status in ('pending', 'approved', 'rejected', 'cancelled'))
);

create index if not exists leave_requests_employee_id_idx
  on public.leave_requests (employee_id);

create index if not exists leave_requests_status_idx
  on public.leave_requests (status);
